### ISSUE TITLE
Error: ERRTIMEDOUT

### ISSUE THREAD

**Issue by fabiotheo** [NumminorihSF/ami-io#36]
When I make action, after the conclusion of the action and after many seconds, I aways receive a message error from ami-io. 

`Error: ERRTIMEDOUT
    at Client.<anonymous> (/home/ipcom/movidesk/node_modules/ami-io/lib/index.js:300:82)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

Why this error happens?

**Comment by NumminorihSF** [comment]
This looks like an issue with tcp-connection. It's possible that your server drops the connecttion.

**Comment by OkaySoft** [comment]
The problem still persists. The problem is observed absolute every time the application is started.

node js v16.14.2
`Error: ERRTIMEDOUT
at Client.<anonymous> (/home/bot/node_modules/ami-io/lib/index.js:300:82)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)`

How can I catch this exception?
